version: "3.9"

services:
  api-gateway:
    container_name: api-gateway
    ports:
      - "3003:3003"
    environment:
      PORT: 3003
      JWT_SECRET: mysecretkey
    depends_on:
      - auth
      - product
      - order
    image: trinhvanvu/api-gateway:latest
    build:
      context: ./api-gateway
      dockerfile: Dockerfile

  auth:
    container_name: auth
    ports:
      - "3000:3000"
    env_file: ./auth/.env
    depends_on:
      - mongo
    image: trinhvanvu/auth:latest
    build:
      context: ./auth
      dockerfile: Dockerfile


  product:
    container_name: product
    ports:
      - "3001:3001"
    env_file: ./product/.env
    depends_on:
      - mongo
      - rabbitmq
    image: trinhvanvu/product:latest
    build:
      context: ./product
      dockerfile: Dockerfile


  order:
    container_name: order
    ports:
      - "3002:3002"
    env_file: ./order/.env
    depends_on:
      - mongo
      - rabbitmq
    image: trinhvanvu/order:latest
    build:
      context: ./order
      dockerfile: Dockerfile


  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  mongo_data:
