version: "3.9"

services:
  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "3003:3003"
    environment:
      PORT: 3003
      JWT_SECRET: mysecretkey
    depends_on:
      - auth
      - product
      - order
    

  auth:
    build:
      context: ./auth
    container_name: auth
    ports:
      - "3000:3000"
    env_file: ./auth/.env
    depends_on:
      - mongo
    

  product:
    build:
      context: ./product
    container_name: product
    ports:
      - "3001:3001"
    env_file: ./product/.env
    depends_on:
      - mongo
      - rabbitmq
 

  order:
    build:
      context: ./order
    container_name: order
    ports:
      - "3002:3002"
    env_file: ./order/.env
    depends_on:
      - mongo
      - rabbitmq
    

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:  
      - "5672:5672"
      - "15672:15672"

volumes:
  mongo_data:
